USE [master]
GO

/****** Object:  Database [AdoExecutorTestDb]    Script Date: 3/3/2015 7:51:52 PM ******/
CREATE DATABASE [AdoExecutorTestDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdoExecutorTestDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\AdoExecutorTestDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AdoExecutorTestDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\AdoExecutorTestDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AdoExecutorTestDb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdoExecutorTestDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdoExecutorTestDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AdoExecutorTestDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdoExecutorTestDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdoExecutorTestDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdoExecutorTestDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdoExecutorTestDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdoExecutorTestDb] SET  MULTI_USER 
GO

ALTER DATABASE [AdoExecutorTestDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdoExecutorTestDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdoExecutorTestDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdoExecutorTestDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdoExecutorTestDb] SET  READ_WRITE 
GO


